name: Drift Detection Pipeline

on:
  workflow_dispatch:
    inputs:
      baseline_size:
        description: "Number of baseline articles"
        required: false
        default: "500"
      test_size:
        description: "Number of test articles"
        required: false
        default: "500"
      batch_size:
        description: "Batch size for processing"
        required: false
        default: "50"

jobs:
  run-drift-detection:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure environment
        run: |
          mkdir -p config
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > config/.env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> config/.env
          echo "SENTIMENT_MODEL=cardiffnlp/twitter-roberta-base-sentiment-latest" >> config/.env
          echo "EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2" >> config/.env
          echo "BASELINE_SAMPLE_SIZE=${{ github.event.inputs.baseline_size }}" >> config/.env
          echo "TEST_SAMPLE_SIZE=${{ github.event.inputs.test_size }}" >> config/.env
          echo "BATCH_SIZE=${{ github.event.inputs.batch_size }}" >> config/.env
          echo "KL_DIVERGENCE_THRESHOLD=0.05" >> config/.env
          echo "COSINE_SIMILARITY_THRESHOLD=0.85" >> config/.env

      - name: Run drift detection pipeline
        run: |
          python -u scripts/run_drift_detection.py

      - name: Pipeline completed
        if: success()
        run: |
          echo "✅ Pipeline completed successfully!"
          echo "Check your Supabase database for results."
